# Ubuntu Template
---

- name: Check if VM ID 121 exists
  shell: qm list | grep -q ' 121 '
  register: vm_exists
  ignore_errors: true
  changed_when: false

- block:

    - name: Create a new VM
      shell: qm create 121 --name Ubuntu-template --memory 1024 --net0 virtio,bridge=vmbr0
      args:
        executable: /bin/bash

    - name: Import disk to Proxmox
      shell: qm importdisk 121 /var/lib/vz/template/iso/jammy-server-cloudimg-amd64-disk-kvm.img local-lvm
      args:
        executable: /bin/bash

    - name: Set VM SCSI hardware
      shell: qm set 121 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-121-disk-0
      args:
        executable: /bin/bash

    - name: Set cloud-init drive
      shell: qm set 121 --ide2 local-lvm:cloudinit --boot c --bootdisk scsi0 --serial0 socket --vga serial0
      args:
        executable: /bin/bash

    - name: Resize the disk
      shell: qm resize 121 scsi0 +8G
      args:
        executable: /bin/bash

    - name: Convert VM to template
      shell: qm template 121
      args:
        executable: /bin/bash
  when: vm_exists.rc != 0