# Debian 11 Template
---

- name: Check if VM ID 452 exists
  shell: qm list | grep -q ' 452 '
  register: vm_exists
  ignore_errors: true
  changed_when: false

- block:

    - name: Create a new VM
      shell: qm create 452 --name debian11-template --memory 1024 --net0 virtio,bridge=vmbr0
      args:
        executable: /bin/bash

    - name: Import disk to Proxmox
      shell: qm importdisk 452 /var/lib/vz/template/iso/debian-11-generic-amd64.qcow2 local-lvm
      args:
        executable: /bin/bash

    - name: Set VM SCSI hardware
      shell: qm set 452 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-452-disk-0
      args:
        executable: /bin/bash

    - name: Set cloud-init drive
      shell: qm set 452 --ide2 local-lvm:cloudinit --boot c --bootdisk scsi0 --serial0 socket --vga serial0
      args:
        executable: /bin/bash

    - name: Resize the disk
      shell: qm resize 452 scsi0 +8G
      args:
        executable: /bin/bash

    - name: Convert VM to template
      shell: qm template 452
      args:
        executable: /bin/bash
  when: vm_exists.rc != 0
