# Debian 11 Template
---

    - name: Clone VM from template
      shell: qm clone 130 131 --name vm-from-template --full true
      args:
        executable: /bin/bash

    - name: Set VM cloud-init configuration
      shell: |
        qm set 131 --ciuser "{{ hostvars['proxmox']['cloud_init_user'] }}" \
                  --cipassword "{{ hostvars['proxmox']['cloud_init_password'] }}" \
                  --ipconfig0 ip="{{ hostvars['proxmox']['cloud_init_ip'] }}" \
                  --sshkeys /path/to/public_keys.pub
      args:
        executable: /bin/bash

    - name: Start the cloned VM
      shell: qm start 131
      args:
        executable: /bin/bash
