# Centos 7 VM
---

- name: Check if VM ID 3515 already exists
  shell: qm list | grep -q ' 3515 '
  register: vm_exists
  ignore_errors: true
  changed_when: false

- name: Centos 7 Clone VM from template if not exists
  shell: qm clone 3514 3515 --name centos7 --full true
  args:
    executable: /bin/bash
  when: vm_exists.rc != 0

- name: Centos 7 Notify VM already exists
  debug:
    msg: "VM ID 3515 already exists, skipping clone."
  when: vm_exists.rc == 0

- name: Centos 7 Set CPU Core and RAM
  shell: "qm set 3515 --cores 1 --sockets 2 --memory 2048 --numa 1 --cpu host"
  args:
    executable: /bin/bash

- name: Centos 7 Set disk size
  shell: "qm resize 3515 scsi0 +50G"
  args:
    executable: /bin/bash

- name: Centos 7 Set cloud-init user
  shell: qm set 3515 --ciuser "{{ hostvars['proxmox']['cloud_init_user'] }}"
  args:
    executable: /bin/bash

- name: Centos 7 Set cloud-init password
  shell: qm set 3515 --cipassword "{{ hostvars['proxmox']['cloud_init_password'] }}"
  args:
    executable: /bin/bash

- name: Centos 7 Set cloud-init IP and gateway configuration
  shell: qm set 3515 --ipconfig0 ip="{{ hostvars['proxmox']['cloud_init_ip'] }},gw={{ hostvars['proxmox']['cloud_init_gw'] }}"
  args:
    executable: /bin/bash

- name: Centos 7 Copy SSH public key to Proxmox server under user directory
  copy:
    src: files/ssh_key.pub
    dest: "/root/centos_key.pub"
    owner: root
    group: root
    mode: '0644'

- name: Centos 7 Set SSH public key for the VM using cloud-init
  shell: qm set 3515 --sshkey /root/centos_key.pub
  args:
    executable: /bin/bash
