# Steps by Step
---

- name: "Download or Copy Image" 
  ansible.builtin.import_tasks: 00_check_iso.yml

- name: "Create A Ubuntu Template" 
  ansible.builtin.import_tasks: 01_ubuntu_temp.yml

- name: "Create A Ubuntu VM" 
  ansible.builtin.import_tasks: 01_ubuntu_vm.yml

- name: "Create A Debian Template" 
  ansible.builtin.import_tasks: 02_debian_temp.yml

- name: "Create A Debian VM" 
  ansible.builtin.import_tasks: 02_debian_vm.yml

# - name: "Create A Centos7 Template" 
#   ansible.builtin.import_tasks: 03_centos_temp.yml

# - name: "Create A Centos7 VM" 
#   ansible.builtin.import_tasks: 03_centos_vm.yml